{% set name = "fastscapelib-f2py" %}
{% set version = "2.8.1" %}
{% set sha256 = "fbb4b6e107f40e2b7792c551abb6423fbd2c35aa6edac824617fe9a0e46161e1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fastscape-lem/fastscapelib-fortran/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('c') }}              # [unix]
    - cmake
  host:
    - python
    - scikit-build
    - pip
    - wheel
    - setuptools
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fastscapelib_fortran

about:
  home: https://github.com/fastscape-lem/fastscapelib-fortran
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Library for landscape evolution modeling (Python bindings)'
  description: |
    A Fortran library that implements efficient algorithms
    for landscape evolution modeling.
    This conda package provides Python bindings (compiled using f2py).

extra:
  recipe-maintainers:
    - benbovy
